trying publish to github

diff --git a/.github/workflows/helm-publish.yaml b/.github/workflows/helm-publish.yaml
--- a/.github/workflows/helm-publish.yaml
+++ b/.github/workflows/helm-publish.yaml
@@ -14,3 +14,48 @@ jobs:
     secrets:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
+
+  githubPublish:
+    name: Push Helm Chart to Github
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Log in to GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Set up Helm
+        uses: azure/setup-helm@v4
+        with:
+          version: v3.14.4
+
+      - name: Extract version from Chart.yaml
+        id: chart_version
+        run: |
+          VERSION=$(yq e '.version' ${{ inputs.chart-path }}/Chart.yaml)
+          APP_VERSION=$(yq e '.appVersion' ${{ inputs.chart-path }}/Chart.yaml)
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
+
+      - name: Package Helm chart
+        run: |
+          helm package ${{ inputs.chart-path }} \
+            --version ${{ steps.chart_version.outputs.version }} \
+            --app-version ${{ steps.chart_version.outputs.app_version }}
+
+
+      - name: Push Helm chart to GitHub Container Registry
+        run: |
+          FILE=$(ls *.tgz | head -n1)
+          if [ -z "$FILE" ]; then
+            echo "Error: No packaged chart found!"
+            exit 1
+          fi
+          echo "Pushing $FILE to GitHub Container Registry..."
+          helm push $FILE oci://ghcr.io/besqpin/helm-base:${{ steps.chart_version.outputs.version }}
